name: go-test
on:
  push:
  pull_request:
  schedule:
    - cron: '49 4 20 * *'

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.17', '1.18', '1.19', '1.20', '1.21', '1.22']

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: go test -v ./...
